/* TrekkingMap service worker — GENERATED by scripts/build_sw.py. Do not edit.
 *
 * Makes the app work with no connection at all after one visit.
 *
 *   App shell (32 files, 11.3 MB) — precached on install, then
 *   served cache-first. This is what lets the page boot offline.
 *
 *   Map tiles — cached as they are viewed, never prefetched. Caching what the
 *   user actually looked at is ordinary browser behaviour; speculatively
 *   downloading a region is bulk downloading and violates the OpenStreetMap and
 *   OpenTopoMap tile usage policies. The tile cache is capped and evicted
 *   oldest-first so it cannot grow without bound.
 *
 *   Overpass — never cached here. The app keeps hut regions in IndexedDB, which
 *   it can reason about and show the size of; a second opaque copy in the SW
 *   would double the storage and answer to nobody.
 */

var VERSION = 'fddd70b1fcb9';
var SHELL_CACHE = 'tm-shell-' + VERSION;
var TILE_CACHE  = 'tm-tiles-v1';
var TILE_LIMIT  = 1200;                 // roughly 25-30 MB of raster tiles

var SHELL = [
  "./index.html",
  "./styles.css",
  "./manifest.json",
  "./vendor/leaflet.css",
  "./vendor/leaflet.js",
  "./vendor/images/marker-icon.png",
  "./vendor/images/marker-icon-2x.png",
  "./vendor/images/marker-shadow.png",
  "./vendor/images/layers.png",
  "./vendor/images/layers-2x.png",
  "./planner.js",
  "./tiles.js",
  "./search.js",
  "./gpx.js",
  "./route.js",
  "./cache.js",
  "./contextmenu.js",
  "./locate.js",
  "./offline.js",
  "./app.js",
  "./data/dem.js",
  "./data/contours_major.js",
  "./data/contours_minor.js",
  "./data/huts.js",
  "./data/peaks.js",
  "./data/water.js",
  "./data/avml.js",
  "./data/routes.js",
  "./data/sample_gpx.js",
  "./icon-192.png",
  "./icon-512.png",
  "./apple-touch-icon.png"
];

self.addEventListener('install', function (e) {
  e.waitUntil(
    caches.open(SHELL_CACHE)
      .then(function (c) { return c.addAll(SHELL); })
      .then(function () { return self.skipWaiting(); })
  );
});

self.addEventListener('activate', function (e) {
  e.waitUntil(
    caches.keys().then(function (names) {
      return Promise.all(names.map(function (n) {
        // Keep the tile cache across releases — those bytes are expensive to
        // refetch and the tiles themselves have not changed.
        if (n === SHELL_CACHE || n === TILE_CACHE) return null;
        return caches.delete(n);
      }));
    }).then(function () { return self.clients.claim(); })
  );
});

function isTile(url) {
  return /tile\.openstreetmap\.org|tile\.opentopomap\.org|tile-cyclosm|arcgisonline\.com/.test(url);
}

/** Oldest-first eviction. Cache API preserves insertion order in keys(). */
function trimTiles() {
  return caches.open(TILE_CACHE).then(function (c) {
    return c.keys().then(function (keys) {
      if (keys.length <= TILE_LIMIT) return;
      return Promise.all(keys.slice(0, keys.length - TILE_LIMIT)
        .map(function (k) { return c.delete(k); }));
    });
  });
}

self.addEventListener('fetch', function (e) {
  var req = e.request;
  if (req.method !== 'GET') return;
  var url = req.url;

  // Overpass stays online-only; the app has its own inspectable cache.
  if (/overpass|maps\.mail\.ru|nominatim/.test(url)) return;

  if (isTile(url)) {
    e.respondWith(
      caches.open(TILE_CACHE).then(function (c) {
        return c.match(req).then(function (hit) {
          if (hit) return hit;
          return fetch(req).then(function (res) {
            // Opaque responses cannot be inspected, but they replay fine for
            // <img>, and Leaflet loads tiles as images.
            if (res && (res.ok || res.type === 'opaque')) {
              c.put(req, res.clone());
              trimTiles();
            }
            return res;
          }).catch(function () {
            // Offline and never seen: let Leaflet's own retry/placeholder handle it.
            return new Response('', { status: 504, statusText: 'offline' });
          });
        });
      })
    );
    return;
  }

  // Everything else in our own scope: cache first, so a cold start with no
  // network still boots. Refresh in the background when we do have one.
  e.respondWith(
    caches.match(req).then(function (hit) {
      if (hit) {
        fetch(req).then(function (res) {
          if (res && res.ok) caches.open(SHELL_CACHE).then(function (c) { c.put(req, res); });
        }).catch(function () { /* offline: the cached copy is the answer */ });
        return hit;
      }
      return fetch(req).then(function (res) {
        if (res && res.ok && new URL(url).origin === self.location.origin) {
          var copy = res.clone();
          caches.open(SHELL_CACHE).then(function (c) { c.put(req, copy); });
        }
        return res;
      }).catch(function () {
        // A navigation with nothing cached: fall back to the app shell.
        if (req.mode === 'navigate') return caches.match('./index.html');
        return new Response('', { status: 504, statusText: 'offline' });
      });
    })
  );
});

// The page asks for these to show cache size and to force an update.
self.addEventListener('message', function (e) {
  var d = e.data || {};
  if (d.type === 'VERSION') {
    e.source.postMessage({ type: 'VERSION', version: VERSION, shellFiles: SHELL.length });
  } else if (d.type === 'TILE_COUNT') {
    caches.open(TILE_CACHE).then(function (c) { return c.keys(); })
      .then(function (k) { e.source.postMessage({ type: 'TILE_COUNT', count: k.length }); });
  } else if (d.type === 'CLEAR_TILES') {
    caches.delete(TILE_CACHE)
      .then(function () { e.source.postMessage({ type: 'TILES_CLEARED' }); });
  }
});
